### ISSUE TITLE
Issues regarding the computation of FLOPS with thop

### ISSUE THREAD

**Issue by Guanghan** [huawei-noah/vega#69]
In model_statistics.py, the FLOPS is computed with the 3rd party package "thop". In their [GitHub repo](https://github.com/sovrasov/flops-counter.pytorch/issues/16), it has been explained that the output of profile is actually MACs instead of FLOPS. 

It is even puzzling with this line of code: ` self.gflops, self.kparams = flops_count * 1600 * 1e-9, params_count * 1e-3`
 
Multiplying 1e-9 is to make it GMACS, but why multiplying 1600?

**Comment by gnkn0028** [comment]
Thank you for your comment. You are correct that the FLOPS it calculates is actually MACs. The reason why 1600 is multiplied is that in some algorithms, the academic is comparing FLOPS of different models with a high resolution. Since the models are pure CNNs, we divide both height and width by 40 times, and multiply the final MACs by 1600.

We notice that it is not good to do so as a module, and we'll fix it in the next patch.

**Comment by zhangjiajin** [comment]
We have released a new version and this issue has been resolved. Please try again.
@Guanghan

**Comment by Guanghan** [comment]
Thank you for your comments and detailed explanation.
