### ISSUE TITLE
One question about CARS_NSGA (pNSGA-III).

### ISSUE THREAD

**Issue by Sunrisulfr** [huawei-noah/vega#99]
In 'vega/vega/algorithms/nas/cars/nsga3.py':
...
Fs = []
    for obj in objs:
        Fs.append(NonDominatedSorting(np.vstack((1 / target, obj))))
        Fs.append(NonDominatedSorting(np.vstack((1 / target, 1 / obj))))
...

Hello! I have a question about pNSGA-III in CARS. In the above code, there are two sets of NonDominatedSorted in the list Fs. They are [1/accuray, model_size] and [1/accuray, 1/model_size]. But in the paper, it's described as "For the proposed pNSGA-III, besides considering the number of parameters and accuracy, we also conduct a
non-dominated sorting algorithm that considers the increasing speed of the accuracy and the number of parameters." I can't understand the discrepancy between the two. Did I not find the correct location of the pNSGA-III-related code?
Looking forward to your answer. Thank you!

**Comment by zhaohui-yang** [comment]
Dear Sunrisulfr,

Firstly, non-dominated sorting considers model size and accuracy (larger models with higher accuracy and smaller models with lower accuracy, the left side sorting in the following figure in the main paper). Secondly, non-dominated sorting considers the model size and increasing speed of accuracy (larger models with slower accuracy increasing speed and smaller models with faster accuracy increasing speed, the right side sorting in the following figure in the main paper).

**Comment by Sunrisulfr** [comment]
Thank you!
How is the increasing speed of accuracy calculated in the code?
"
Fs.append(NonDominatedSorting(np.vstack((1 / target, obj))))
Fs.append(NonDominatedSorting(np.vstack((1 / target, 1 / obj))))
"
Neither obj nor target seem to be increasing speed of accuracy.

**Comment by zhaohui-yang** [comment]
Assuming 'target' is accuracy we want to maximize, 'obj' is one of the objectives we want to minimize.

We first minimize accuracy and objective, which is minimizing 1/target and obj.

Then we minimize the models (right side) by minimizing increasing speed and maximizing 'obj'. The increasing speed equals to 'target'/ epoch, therefore, the constant epoch could be removed because the constant value does not affect the nsga. This is minimizing both 1/target and 1/obj.
